name: backbit-dev
services:
  db:
    image: mysql
    container_name: backbit_mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=DevBackbit!MySQL
      - MYSQL_DATABASE=backbit
    command: mysqld --sql_mode=""
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:4-management
    container_name: backbit_rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_NODE_PORT=5672
      - RABBITMQ_DEFAULT_USER=backbit
      - RABBITMQ_DEFAULT_PASS=DevBackbit!RabbitMQ
    ports:
      - 15672:15672
      - 5672:5672

volumes:
  mysql_data:
    driver: local