name: Dev
on:
  push:
    branches: [ 'main' ]

env:
  NODE_VERSION: '20'

jobs:
  version:
    runs-on: self-hosted
    outputs:
      version: ${{ env.VERSION }}

    steps:
      - name: Generate Version
        uses: Nyffels-IT/github-actions-calver-version-generator@v1.0.1
        with:
          suffix: 'DEV'

      - name: Show version
        run: 'echo Version: ${{ env.VERSION }}'

  agent-conjob:
    runs-on: ubuntu-latest
    needs: version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install
        working-directory: agents/cronjob

      - name: Build TypeScript
        run: npm run build
        working-directory: agents/cronjob

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./agents/cronjob
          file: ./agents/cronjob/Dockerfile
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/backbit-agent-cronjob:${{ needs.version.outputs.VERSION }}, ${{ vars.DOCKER_USERNAME }}/backbit-agent-cronjob:dev

  agent-mysql:
    runs-on: ubuntu-latest
    needs: version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install
        working-directory: agents/mysql

      - name: Build TypeScript
        run: npm run build
        working-directory: agents/mysql

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./agents/mysql
          file: ./agents/mysql/Dockerfile
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/backbit-agent-mysql:${{ needs.version.outputs.VERSION }}, ${{ vars.DOCKER_USERNAME }}/backbit-agent-mysql:dev